#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Project Hazel"
  https://create.arduino.cc/cloud/things/27c3ccb9-3233-440b-9f36-3b70d989db76 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch switch_1;
  CloudSwitch switch_2;
  CloudSwitch switch_3;
  CloudSwitch switch_4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

/*
   GPIO PINs

   Which we will used to to controll the Relay and physical Switch
*/
#define RELAY_OUTPUT_1 4  // D2
#define RELAY_OUTPUT_2 5  // D1
#define RELAY_OUTPUT_3 12 // D6
#define RELAY_OUTPUT_4 14 // D5

#define SWITCH_INPUT_1 13 // D7
#define SWITCH_INPUT_2 D3 // D3
#define SWITCH_INPUT_3 3  // RX
#define SWITCH_INPUT_4 16 // D8 -- Semi-functional at the momemt

void setup() {
  // Set ALl Switchs as Input
  pinMode(SWITCH_INPUT_1, INPUT_PULLUP);
  pinMode(SWITCH_INPUT_2, INPUT_PULLUP);
  pinMode(SWITCH_INPUT_3, INPUT_PULLUP);
#if defined(SWITCH_INPUT_4)
  pinMode(SWITCH_INPUT_4, INPUT_PULLUP);
#endif

  // Set ALl Relay as Output
  pinMode(RELAY_OUTPUT_1, OUTPUT);
  pinMode(RELAY_OUTPUT_2, OUTPUT);
  pinMode(RELAY_OUTPUT_3, OUTPUT);
  pinMode(RELAY_OUTPUT_4, OUTPUT);

  //Initialize all pin to LOW (0/OFF)
  digitalWrite(RELAY_OUTPUT_1, HIGH);
  digitalWrite(RELAY_OUTPUT_2, HIGH);
  digitalWrite(RELAY_OUTPUT_3, HIGH);
  digitalWrite(RELAY_OUTPUT_4, HIGH);

  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  delay(300);
  
}




/*
  Since Switch1 is READ_WRITE variable, onSwitch1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch1Change()  {
  // Add your code here to act upon Switch1 change
  digitalWrite(RELAY_OUTPUT_1, !switch_1);
}

/*
  Since Switch2 is READ_WRITE variable, onSwitch2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch2Change()  {
  // Add your code here to act upon Switch2 change
  digitalWrite(RELAY_OUTPUT_2, !switch_2);
}

/*
  Since Switch3 is READ_WRITE variable, onSwitch3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch3Change()  {
  // Add your code here to act upon Switch3 change
  digitalWrite(RELAY_OUTPUT_3, !switch_3);
}

/*
  Since Switch4 is READ_WRITE variable, onSwitch4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch4Change()  {
  // Add your code here to act upon Switch4 change
  digitalWrite(RELAY_OUTPUT_4, !switch_4);
}