/*
  Sketch generated by the Arduino IoT Cloud Thing "Project Hazel"
  https://create.arduino.cc/cloud/things/27c3ccb9-3233-440b-9f36-3b70d989db76

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch switch_1;
  CloudSwitch switch_2;
  CloudSwitch switch_3;
  CloudSwitch switch_4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

/*
   GPIO PINs

   Which we will used to to controll the Relay and physical Switch
*/
#define RELAY_OUTPUT_1 4  // D2
#define RELAY_OUTPUT_2 5  // D1
#define RELAY_OUTPUT_3 12 // D6
#define RELAY_OUTPUT_4 14 // D5

#define SWITCH_INPUT_1 13 // D7
#define SWITCH_INPUT_2 D3 // D3
#define SWITCH_INPUT_3 3  // RX
#define SWITCH_INPUT_4 16 // D8 -- Semi-functional at the momemt

/*
   Previous Relay State
*/
bool prev_state_switch_1 = 0;
bool prev_state_switch_2 = 0;
bool prev_state_switch_3 = 0;
bool prev_state_switch_4 = 0;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Set ALl Switchs as Input
  pinMode(SWITCH_INPUT_1, INPUT_PULLUP);
  pinMode(SWITCH_INPUT_2, INPUT_PULLUP);
  pinMode(SWITCH_INPUT_3, INPUT_PULLUP);
#if defined(SWITCH_INPUT_4)
  pinMode(SWITCH_INPUT_4, INPUT_PULLUP);
#endif

  // Set ALl Relay as Output
  pinMode(RELAY_OUTPUT_1, OUTPUT);
  pinMode(RELAY_OUTPUT_2, OUTPUT);
  pinMode(RELAY_OUTPUT_3, OUTPUT);
  pinMode(RELAY_OUTPUT_4, OUTPUT);

  //Initialize all pin to LOW (0/OFF)
  digitalWrite(RELAY_OUTPUT_1, HIGH);
  digitalWrite(RELAY_OUTPUT_2, HIGH);
  digitalWrite(RELAY_OUTPUT_3, HIGH);
  digitalWrite(RELAY_OUTPUT_4, HIGH);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // delay(300);
  bool switchState_1 = digitalRead(SWITCH_INPUT_1);
  bool switchState_2 = digitalRead(SWITCH_INPUT_2);
  bool switchState_3 = digitalRead(SWITCH_INPUT_3);
#if defined(SWITCH_INPUT_4)
  bool switchState_4 = digitalRead(SWITCH_INPUT_4);
#endif

  // Condition to Check if Switch is ON
  if (switchState_1 == HIGH) {
    switch_1 = HIGH;
    digitalWrite(RELAY_OUTPUT_1, switch_1);
    prev_state_switch_1 = true;
    delay(100);
  }
  if (switchState_2 == HIGH) {
    switch_2 = HIGH;
    digitalWrite(RELAY_OUTPUT_2, switch_2);
    prev_state_switch_2 = true;
    delay(100);
  }
  if (switchState_3 == HIGH) {
    switch_3 = HIGH;
    digitalWrite(RELAY_OUTPUT_3, switch_3);
    prev_state_switch_3 = true;
    delay(100);
  }
#if defined(SWITCH_INPUT_4)
  if (switchState_4 == HIGH) {
    switch_4 = HIGH;
    digitalWrite(RELAY_OUTPUT_4, switch_4);
    prev_state_switch_4 = true;
    delay(100);
  }
#endif
  // Condition to Check if Switch is OFF
  if (prev_state_switch_1 == true && switchState_1 == LOW) {
    switch_1 = LOW;
    digitalWrite(RELAY_OUTPUT_1, switch_1);
    prev_state_switch_1 = false;
    delay(100);
  }
  if (prev_state_switch_2 == true && switchState_2 == LOW) {
    switch_2 = LOW;
    digitalWrite(RELAY_OUTPUT_2, switch_2);
    prev_state_switch_2 = false;
    delay(100);
  }
  if (prev_state_switch_3 == true && switchState_3 == LOW) {
    switch_3 = LOW;
    digitalWrite(RELAY_OUTPUT_3, switch_3);
    prev_state_switch_3 = false;
    delay(100);
  }
#if defined(SWITCH_INPUT_4)
  if (prev_state_switch_4 == true && switchState_4 == LOW) {
    switch_4 = LOW;
    digitalWrite(RELAY_OUTPUT_4, switch_4);
    prev_state_switch_4 = false;
    delay(100);
  }
#endif

}




/*
  Since Switch1 is READ_WRITE variable, onSwitch1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch1Change()  {
  bool state = switch_1;
  if (state)
    digitalWrite(RELAY_OUTPUT_1, LOW);
  else
    digitalWrite(RELAY_OUTPUT_1, HIGH);
}

/*
  Since Switch2 is READ_WRITE variable, onSwitch2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch2Change()  {
  bool state = switch_2;
  if (state)
    digitalWrite(RELAY_OUTPUT_2, LOW);
  else
    digitalWrite(RELAY_OUTPUT_2, HIGH);
}

/*
  Since Switch3 is READ_WRITE variable, onSwitch3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch3Change()  {
  bool state = switch_3;
  if (state)
    digitalWrite(RELAY_OUTPUT_3, LOW);
  else
    digitalWrite(RELAY_OUTPUT_3, HIGH);
}

#if defined(SWITCH_INPUT_4)
/*
  Since Switch4 is READ_WRITE variable, onSwitch4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitch4Change()  {
  bool state = switch_4;
  if (state)
    digitalWrite(RELAY_OUTPUT_4, LOW);
  else
    digitalWrite(RELAY_OUTPUT_4, HIGH);
}
#endif
