:Author: Apavayan Sinha
:Email: info@apavayan.com
:Date: 03/01/2022
:Revision: version# 1
:License: Public Domain

= Project: Hazel

A smiple 4 relay with 4 switch IoT Extension using Arduino Cloud.

=== Folder structure

....
 Project_Hazel_jan03a                => Arduino sketch folder
  ├── Project_Hazel_jan03a.ino       => main Arduino file
  ├── arduino_secrets.h.example      => example file for arduino_secrets.h to store wifi name and password.
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 
{Email}

=== TODO:
Add Offline scheduling to accept values form Alexa.

=== BOM
Add the bill of the materials you need for this project.

|===
| Part name      | Part number | Quantity
| On/Off Switch  |             | 4      
| 4 Channel Relay Module |     | 1     
| ESP8266        | NodeMCU     | 1
| 220V AC to 5V DC 2Amp Circuit Board | SMPS | 1  
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
