// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "27c3ccb9-3233-440b-9f36-3b70d989db76";
const char DEVICE_LOGIN_NAME[]  = "0fd355a3-c7b8-4d63-8574-7fce7fa45a51";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSwitch1Change();
void onSwitch2Change();
void onSwitch3Change();
void onSwitch4Change();

CloudSwitch switch_1;
CloudSwitch switch_2;
CloudSwitch switch_3;
CloudSwitch switch_4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(switch_1, READWRITE, ON_CHANGE, onSwitch1Change);
  ArduinoCloud.addProperty(switch_2, READWRITE, ON_CHANGE, onSwitch2Change);
  ArduinoCloud.addProperty(switch_3, READWRITE, ON_CHANGE, onSwitch3Change);
  ArduinoCloud.addProperty(switch_4, READWRITE, ON_CHANGE, onSwitch4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
